# Generated by Django 5.2 on 2025-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcasts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('numero_destinatario', models.CharField(max_length=20, verbose_name='Numero Destinatário')),
                ('status_envio', models.CharField(choices=[('Enviado com sucesso', 'Enviado com sucesso'), ('Erro ao enviar', 'Erro ao enviar')], default=None, max_length=50, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'db_table': 'broadcasts_broadcast',
                'ordering': ('id',),
            },
        ),
    ]
